#ifndef MINIOS_ABI_ERRNO_H
#define MINIOS_ABI_ERRNO_H

#define MINIOS_ENOENT 2
#define MINIOS_EIO 5
#define MINIOS_EBADF 9
#define MINIOS_ECHILD 10
#define MINIOS_EAGAIN 11
#define MINIOS_ENOMEM 12
#define MINIOS_EFAULT 14
#define MINIOS_EEXIST 17
#define MINIOS_ENOTDIR 20
#define MINIOS_EISDIR 21
#define MINIOS_EINVAL 22
#define MINIOS_ENOSPC 28
#define MINIOS_ENOSYS 38
#define MINIOS_ENOTEMPTY 39

#endif
