#ifndef MINIOS_ABI_INPUT_H
#define MINIOS_ABI_INPUT_H

#define MINIOS_KEY_DELETE 0x7FU
#define MINIOS_KEY_LEFT 0x80U
#define MINIOS_KEY_RIGHT 0x81U
#define MINIOS_KEY_UP 0x82U
#define MINIOS_KEY_DOWN 0x83U
#define MINIOS_KEY_HOME 0x84U
#define MINIOS_KEY_END 0x85U

#endif
