#ifndef MINIOS_ABI_MINIFS_H
#define MINIOS_ABI_MINIFS_H

/* MiniFS 磁盘 ABI：所有多字节字段均为 little-endian。 */
#define MINIFS_MAGIC 0x3153464DU
#define MINIFS_VERSION 1U
#define MINIFS_BLOCK_SIZE 4096U
#define MINIFS_INODE_SIZE 64U
#define MINIFS_DIRECTORY_ENTRY_SIZE 64U
#define MINIFS_DIRECT_COUNT 10U
#define MINIFS_INDIRECT_COUNT 1024U
#define MINIFS_NAME_MAX 58U
#define MINIFS_MODE_REGULAR 1U
#define MINIFS_MODE_DIRECTORY 2U
#define MINIFS_ENTRY_UNUSED 0U
#define MINIFS_ENTRY_REGULAR 1U
#define MINIFS_ENTRY_DIRECTORY 2U

#define MINIFS_SUPERBLOCK_HEADER_SIZE 56U
#define MINIFS_SUPERBLOCK_MAGIC_OFFSET 0U
#define MINIFS_SUPERBLOCK_VERSION_OFFSET 4U
#define MINIFS_SUPERBLOCK_BLOCK_SIZE_OFFSET 8U
#define MINIFS_SUPERBLOCK_TOTAL_BLOCKS_OFFSET 12U
#define MINIFS_SUPERBLOCK_TOTAL_INODES_OFFSET 16U
#define MINIFS_SUPERBLOCK_BLOCK_BITMAP_START_OFFSET 20U
#define MINIFS_SUPERBLOCK_BLOCK_BITMAP_BLOCKS_OFFSET 24U
#define MINIFS_SUPERBLOCK_INODE_BITMAP_START_OFFSET 28U
#define MINIFS_SUPERBLOCK_INODE_BITMAP_BLOCKS_OFFSET 32U
#define MINIFS_SUPERBLOCK_INODE_TABLE_START_OFFSET 36U
#define MINIFS_SUPERBLOCK_INODE_TABLE_BLOCKS_OFFSET 40U
#define MINIFS_SUPERBLOCK_DATA_START_OFFSET 44U
#define MINIFS_SUPERBLOCK_ROOT_INODE_OFFSET 48U
#define MINIFS_SUPERBLOCK_CHECKSUM_OFFSET 52U

#define MINIFS_INODE_MODE_OFFSET 0U
#define MINIFS_INODE_LINK_COUNT_OFFSET 2U
#define MINIFS_INODE_SIZE_OFFSET 4U
#define MINIFS_INODE_DIRECT_OFFSET 8U
#define MINIFS_INODE_INDIRECT_OFFSET 48U
#define MINIFS_INODE_CREATED_TICK_OFFSET 52U
#define MINIFS_INODE_MODIFIED_TICK_OFFSET 56U
#define MINIFS_INODE_RESERVED_OFFSET 60U

#define MINIFS_DIRECTORY_INODE_OFFSET 0U
#define MINIFS_DIRECTORY_TYPE_OFFSET 4U
#define MINIFS_DIRECTORY_NAME_OFFSET 5U
#define MINIFS_DIRECTORY_NAME_BYTES 59U

#endif
