#!/usr/bin/env python3
"""从镜像布局生成 Stage 1 使用的 NASM 常量。"""

from __future__ import annotations

import argparse
import json
import os
import tempfile
from pathlib import Path
from typing import NoReturn


SECTOR_SIZE = 512
STAGE2_LOAD_ADDRESS = 0x8000
FIRST_DMA_BOUNDARY = 0x10000
MAX_STAGE2_SECTORS = 127
MAX_DAP_LBA = (1 << 64) - 1


class LayoutError(Exception):
    """表示镜像布局不能安全转换为 Stage 1 常量。"""


def _fail(message: str) -> NoReturn:
    raise LayoutError(message)


def _integer(value: object, name: str) -> int:
    if type(value) is not int:
        _fail(f"{name} 必须是整数")
    assert isinstance(value, int)
    return value


def _load_stage2(layout_path: Path) -> tuple[int, int]:
    try:
        raw = layout_path.read_text(encoding="utf-8")
        layout = json.loads(raw)
    except (OSError, UnicodeError, json.JSONDecodeError) as error:
        _fail(f"无法读取布局 JSON：{error}")

    if type(layout) is not dict:
        _fail("布局顶层必须是 object")
    assert isinstance(layout, dict)
    expected_fields = {
        "format_version",
        "sector_size",
        "image_size_bytes",
        "components",
    }
    if set(layout) != expected_fields:
        _fail("布局顶层 schema 无效")
    if _integer(layout["format_version"], "format_version") != 1:
        _fail("仅支持 format_version=1")
    if _integer(layout["sector_size"], "sector_size") != SECTOR_SIZE:
        _fail("Stage 1 仅支持 512 字节扇区")

    image_size = _integer(layout["image_size_bytes"], "image_size_bytes")
    if image_size <= 0 or image_size % SECTOR_SIZE != 0:
        _fail("image_size_bytes 必须是正的完整扇区倍数")
    image_sectors = image_size // SECTOR_SIZE

    components = layout["components"]
    if type(components) is not list:
        _fail("components 必须是数组")
    stage2_components: list[dict[str, object]] = []
    for index, component in enumerate(components):
        if type(component) is not dict:
            _fail(f"components[{index}] 必须是 object")
        assert isinstance(component, dict)
        if set(component) != {"name", "artifact", "lba", "max_sectors"}:
            _fail(f"components[{index}] schema 无效")
        if component["name"] == "stage2":
            stage2_components.append(component)
    if len(stage2_components) != 1:
        _fail("布局必须且只能包含一个 stage2 组件")

    stage2 = stage2_components[0]
    if type(stage2["artifact"]) is not str or not stage2["artifact"]:
        _fail("stage2.artifact 必须是非空字符串")
    lba = _integer(stage2["lba"], "stage2.lba")
    sector_count = _integer(stage2["max_sectors"], "stage2.max_sectors")
    if not 0 <= lba <= MAX_DAP_LBA:
        _fail("stage2.lba 超出 DAP 64 位 LBA 范围")
    if not 1 <= sector_count <= MAX_STAGE2_SECTORS:
        _fail("stage2.max_sectors 必须位于 1..127")
    if lba + sector_count > image_sectors or lba + sector_count > MAX_DAP_LBA + 1:
        _fail("stage2 区域越过镜像或 DAP LBA 边界")

    first_count = min(
        sector_count,
        (FIRST_DMA_BOUNDARY - STAGE2_LOAD_ADDRESS) // SECTOR_SIZE,
    )
    second_count = sector_count - first_count
    if STAGE2_LOAD_ADDRESS + first_count * SECTOR_SIZE > FIRST_DMA_BOUNDARY:
        _fail("第一个 Stage 2 DAP 跨越 64 KiB DMA 边界")
    if FIRST_DMA_BOUNDARY + second_count * SECTOR_SIZE > 0x20000:
        _fail("第二个 Stage 2 DAP 跨越 64 KiB DMA 边界")
    return lba, sector_count


def _render(lba: int, sector_count: int) -> bytes:
    return (
        "; Generated by tools/generate_boot_layout.py; do not edit.\n"
        f"%define STAGE2_LBA 0x{lba:016X}\n"
        f"%define STAGE2_MAX_SECTORS {sector_count}\n"
    ).encode("ascii")


def _write_atomic(output: Path, payload: bytes) -> None:
    try:
        parent = output.parent
        if not parent.is_dir():
            _fail(f"输出父目录不存在：{parent}")
        descriptor, temporary_name = tempfile.mkstemp(
            prefix=f".{output.name}.", suffix=".tmp", dir=parent
        )
        try:
            with os.fdopen(descriptor, "wb") as stream:
                stream.write(payload)
                stream.flush()
                os.fsync(stream.fileno())
            os.chmod(temporary_name, 0o644)
            os.replace(temporary_name, output)
        except BaseException:
            try:
                os.unlink(temporary_name)
            except FileNotFoundError:
                pass
            raise
    except OSError as error:
        _fail(f"无法原子写入输出：{error}")


def _parse_arguments(arguments: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, allow_abbrev=False)
    parser.add_argument("--layout", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    return parser.parse_args(arguments)


def main(arguments: list[str] | None = None) -> int:
    options = _parse_arguments(arguments)
    try:
        lba, sector_count = _load_stage2(options.layout)
        _write_atomic(options.output, _render(lba, sector_count))
    except LayoutError as error:
        print(f"generate_boot_layout.py: error: {error}", file=os.sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
